let data = [
    {
        "gender":"female",
        "name":[
            "Miss",
            "Faith",
            "Andrews"
        ],
        "location":[
            "1170",
            "Highfield Road",
            "Donabate",
            "Donegal",
            "Ireland",
            "36442"
        ],
        "email":"faith.andrews@example.com",
        "date":"1989-07-12T21:00:49.966Z","age":33,
        "phone":"011-332-3077","cell":"081-707-4730",
        "picture":"https://randomuser.me/api/portraits/women/2.jpg",
    },{
        "gender":"female",
        "name":[
            "Ms",
            "درسا",
            "موسوی"
        ],
        "location":[
            "8692",
            "میدان امام حسین",
            "رشت",
            "سمنان",
            "Iran",
            "70612"
        ],
        "email":"drs.mwswy@example.com",
        "date":"1952-02-29T02:01:37.329Z","age":70,
        "phone":"014-86041493","cell":"0943-359-5264",
        "picture":"https://randomuser.me/api/portraits/women/53.jpg",
    },{
        "gender":"female",
        "name":[
            "Mrs",
            "Vicenta",
            "Álvarez"
        ],
        "location":[
            "5599",
            "Calle de La Democracia",
            "Palma de Mallorca",
            "Castilla y León",
            "Spain",
            "49311"
        ],
        "email":"vicenta.alvarez@example.com",
        "date":"1961-09-22T06:07:13.917Z","age":60,
        "phone":"905-970-297","cell":"636-695-176",
        "picture":"https://randomuser.me/api/portraits/women/73.jpg",
    },{
        "gender":"female",
        "name":[
            "Ms",
            "Ronalina",
            "Koryak"
        ],
        "location":[
            "2762",
            "Turgenievska",
            "Svitlovodsk",
            "Odeska",
            "Ukraine",
            "19969"
        ],
        "email":"ronalina.koryak@example.com",
        "date":"1959-07-07T22:04:47.194Z","age":63,
        "phone":"(099) A92-5475","cell":"(068) M44-1023",
        "picture":"https://randomuser.me/api/portraits/women/28.jpg",
    },{
        "gender":"male",
        "name":[
            "Mr",
            "Zdorovega",
            "Oleksiienko"
        ],
        "location":[
            "7436",
            "Ivana Rutkovicha",
            "Kriviy Rig",
            "Rivnenska",
            "Ukraine",
            "42185"
        ],
        "email":"zdorovega.oleksiienko@example.com",
        "date":"1993-05-22T03:22:23.361Z","age":29,
        "phone":"(067) R64-6093","cell":"(097) V93-7878",
        "picture":"https://randomuser.me/api/portraits/men/37.jpg",
    },{
        "gender":"female",
        "name":[
            "Ms",
            "هستی",
            "احمدی"
        ],
        "location":[
            "9633",
            "کارگر",
            "ورامین",
            "اردبیل",
            "Iran",
            "65099"
        ],
        "email":"hsty.hmdy@example.com",
        "date":"1992-03-25T16:38:40.029Z","age":30,
        "phone":"055-45265403","cell":"0956-954-1909",
        "picture":"https://randomuser.me/api/portraits/women/11.jpg",
    },{
        "gender":"female",
        "name":[
            "Mrs",
            "Abigail",
            "Lee"
        ],
        "location":[
            "8583",
            "E Pecan St",
            "Townsville",
            "New South Wales",
            "Australia",
            "409"
        ],
        "email":"abigail.lee@example.com",
        "date":"1956-05-29T16:27:54.354Z","age":66,
        "phone":"04-7813-7917","cell":"0497-178-944",
        "picture":"https://randomuser.me/api/portraits/women/0.jpg",
    },{
        "gender":"female",
        "name":[
            "Miss",
            "Hanaé",
            "Lecomte"
        ],
        "location":[
            "3013",
            "Avenue Goerges Clémenceau",
            "Tours",
            "Landes",
            "France",
            "12069"
        ],
        "email":"hanae.lecomte@example.com",
        "date":"1946-09-20T12:05:14.073Z","age":75,
        "phone":"01-70-21-52-66","cell":"06-41-70-86-07",
        "picture":"https://randomuser.me/api/portraits/women/32.jpg",
    },{
        "gender":"male",
        "name":[
            "Mr",
            "Gatusil",
            "Gulchenko"
        ],
        "location":[
            "4335",
            "Anatoliya Petrickogo",
            "Podilsk",
            "Zhitomirska",
            "Ukraine",
            "96618"
        ],
        "email":"gatusil.gulchenko@example.com",
        "date":"1963-06-13T18:06:45.066Z","age":59,
        "phone":"(068) I00-8906","cell":"(099) T24-3066",
        "picture":"https://randomuser.me/api/portraits/men/54.jpg",
    },{
        "gender":"male",
        "name":[
            "Mr",
            "Brayden",
            "Fletcher"
        ],
        "location":[
            "5714",
            "Cherry St",
            "Bendigo",
            "South Australia",
            "Australia",
            "2251"
        ],
        "email":"brayden.fletcher@example.com",
        "date":"2001-05-13T18:26:23.132Z","age":21,
        "phone":"09-2122-4591","cell":"0497-981-928",
        "picture":"https://randomuser.me/api/portraits/men/53.jpg",
    },{
        "gender":"male",
        "name":[
            "Mr",
            "Samatar",
            "Nooijen"
        ],
        "location":[
            "886",
            "Horstingerend",
            "Gerkesklooster",
            "Overijssel",
            "Netherlands",
            "6284 GT"
        ],
        "email":"samatar.nooijen@example.com",
        "date":"1954-09-14T10:19:54.752Z","age":67,
        "phone":"(054) 8903720","cell":"(06) 73567938",
        "picture":"https://randomuser.me/api/portraits/men/83.jpg",
    },{
        "gender":"male",
        "name":[
            "Mr",
            "Gualdim",
            "Martins"
        ],
        "location":[
            "3845",
            "Rua Santos Dumont ",
            "Nova Friburgo",
            "Espírito Santo",
            "Brazil",
            "36825"
        ],
        "email":"gualdim.martins@example.com",
        "date":"1968-05-11T16:05:57.001Z","age":54,
        "phone":"(30) 0993-8495","cell":"(95) 2628-9352",
        "picture":"https://randomuser.me/api/portraits/men/15.jpg",
    },{
        "gender":"female",
        "name":[
            "Mrs",
            "آیلین",
            "صدر"
        ],
        "location":[
            "6766",
            "هلال احمر",
            "ملارد",
            "چهارمحال و بختیاری",
            "Iran",
            "18180"
        ],
        "email":"aylyn.sdr@example.com",
        "date":"1966-01-24T21:30:42.678Z","age":56,
        "phone":"069-86011485","cell":"0912-117-2253",
        "picture":"https://randomuser.me/api/portraits/women/83.jpg",
    },{
        "gender":"female",
        "name":[
            "Ms",
            "Mathilde",
            "Jørgensen"
        ],
        "location":[
            "2924",
            "Gammel Køge Landevej",
            "Gjerlev",
            "Sjælland",
            "Denmark",
            "16191"
        ],
        "email":"mathilde.jorgensen@example.com",
        "date":"1955-10-19T19:27:27.529Z","age":66,
        "phone":"13179964","cell":"87078111",
        "picture":"https://randomuser.me/api/portraits/women/70.jpg",
    },{
        "gender":"female",
        "name":[
            "Mrs",
            "Encarnación",
            "Vicente"
        ],
        "location":[
            "685",
            "Avenida de América",
            "Hospitalet de Llobregat",
            "Melilla",
            "Spain",
            "84422"
        ],
        "email":"encarnacion.vicente@example.com",
        "date":"1951-10-26T17:12:21.263Z","age":70,
        "phone":"941-579-801","cell":"636-701-710",
        "picture":"https://randomuser.me/api/portraits/women/80.jpg",
    },{
        "gender":"male",
        "name":[
            "Mr",
            "Léo",
            "Clement"
        ],
        "location":[
            "1229",
            "Rue de L'Abbé-De-L'Épée",
            "Roubaix",
            "Guyane",
            "France",
            "92672"
        ],
        "email":"leo.clement@example.com",
        "date":"1986-06-17T19:26:56.734Z","age":36,
        "phone":"05-68-46-12-05","cell":"06-45-92-46-18",
        "picture":"https://randomuser.me/api/portraits/men/41.jpg",
    },{
        "gender":"male",
        "name":[
            "Mr",
            "Marcos",
            "Rodríguez"
        ],
        "location":[
            "1172",
            "Calle Mota",
            "Sevilla",
            "Cantabria",
            "Spain",
            "44874"
        ],
        "email":"marcos.rodriguez@example.com",
        "date":"1978-04-16T21:00:26.550Z","age":44,
        "phone":"964-007-444","cell":"624-370-345",
        "picture":"https://randomuser.me/api/portraits/men/45.jpg",
    },{
        "gender":"female",
        "name":[
            "Miss",
            "Edna",
            "Webb"
        ],
        "location":[
            "8100",
            "Preston Rd",
            "Akron",
            "Colorado",
            "United States",
            "35054"
        ],
        "email":"edna.webb@example.com",
        "date":"1979-09-04T15:19:00.671Z","age":42,
        "phone":"(325) 918-0483","cell":"(466) 357-1779",
        "picture":"https://randomuser.me/api/portraits/women/4.jpg",
    },{
        "gender":"female",
        "name":[
            "Mrs",
            "Soledad",
            "Ayala"
        ],
        "location":[
            "6352",
            "Calle Valle",
            "Dzibalchen",
            "Sinaloa",
            "Mexico",
            "60558"
        ],
        "email":"soledad.ayala@example.com",
        "date":"1974-03-12T21:23:27.252Z","age":48,
        "phone":"(674) 816 4381","cell":"(644) 419 4133",
        "picture":"https://randomuser.me/api/portraits/women/66.jpg",
    },{
        "gender":"male",
        "name":[
            "Mr",
            "Emre",
            "Haugan"
        ],
       "location":[
        "8038",
        "Hummerkloa",
            "Rakkestad",
            "Troms - Romsa",
            "Norway",
            "2890"
       ],
        "email":"emre.haugan@example.com",
        "date":"1991-12-31T20:43:27.497Z","age":30,
        "phone":"21855802","cell":"96926341",
        "picture":"https://randomuser.me/api/portraits/men/43.jpg",
    }
]